openapi: 3.0.0

info:
  version: 2.0
  title: 'QthenA Web API'
  description: 'Web Resources Specification (A9) for QthenA'

servers:
- url: https://lbaw2357.lbaw.fe.up.pt
  description: Production server

externalDocs:
 description: Find more info here.
 url: https://git.fe.up.pt/lbaw/lbaw2324/lbaw2357/-/wikis/eap

tags:
- name: 'M01: Authentication'
- name: 'M02: Individual Profile'
- name: 'M03: Commentables & Comments'
- name: 'M04: Search'
- name: 'M05: Administration'
- name: 'M06: Static Pages'

paths:
##############################Authentication##############################
  /login:

    get:
      OperationId: ''

  